from distutils.core import setup

setup(
    name="covid19",
    packages=['covid19'],
    version='0.3',
    license='wtfpl',
    description='covid19 timely stats',
    author='makikaka',
    author_email="mladen.tasevski@gmail.com",
    url='https://github.com/makikaka/covid19',
    download_url='https://github.com/makikaka/covid19/archive/v_03.tar.gz',
    keywords=['covid19', 'http', 'sqlite'],
    install_requires=[
        'sys',
        'http.server',
        'os',
        'utils',
        'logging',
        'datetime',
        'python-memcached',
        'config-parser',
        'sys',
        'sqlite3',
        'json',
        'requests',
        're',
        'bs4',
    ],
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers', 
        'Topic :: Software Development :: Build Tools',
        'License :: OSI Approved :: Do What The F*ck You Want To Public License',
        'Programming Language :: Python :: 3.6',
    ],
)
